# Generated by Django 4.1.7 on 2023-02-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0002_rename_fleet_pnso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='fecha_respuesta',
            field=models.DateField(verbose_name='Fecha Respuesta'),
        ),
    ]
