# Generated by Django 4.1.7 on 2023-02-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0003_alter_pnso_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='estado',
            field=models.CharField(choices=[('A', 'A-NO CUENTA CON INFORMACION SUFICIENTE'), ('B', 'B-NO REQUIERE ACCION DE MITIGACION'), ('C', 'C-ACCION DE MITIGACION EN CURSO'), ('D', 'D-MITIGACION CONCLUIDA'), ('N', 'N-NO CORRESPONDE SER TRAMITADO COMO PNSO')], max_length=1, verbose_name='Estado'),
        ),
    ]
