# Generated by Django 4.1.7 on 2023-02-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0004_alter_pnso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnso',
            name='image_pnso',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
