# Generated by Django 4.1.3 on 2023-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0005_pnso_image_pnso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='estado',
            field=models.CharField(choices=[('AA', 'A-NO CUENTA CON INFORMACION SUFICIENTE'), ('BB', 'B-NO REQUIERE ACCION DE MITIGACION'), ('CC', 'C-ACCION DE MITIGACION EN CURSO'), ('DD', 'D-MITIGACION CONCLUIDA'), ('NN', 'N-NO CORRESPONDE SER TRAMITADO COMO PNSO')], max_length=2, verbose_name='Estado'),
        ),
    ]
