# Generated by Django 4.1.3 on 2023-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0006_alter_pnso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='cierre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='estado',
            field=models.CharField(blank=True, choices=[('AA', 'A-NO CUENTA CON INFORMACION SUFICIENTE'), ('BB', 'B-NO REQUIERE ACCION DE MITIGACION'), ('CC', 'C-ACCION DE MITIGACION EN CURSO'), ('DD', 'D-MITIGACION CONCLUIDA'), ('NN', 'N-NO CORRESPONDE SER TRAMITADO COMO PNSO')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Evento'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Recibido'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Respuesta'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='mitigacion',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Mitigacion'),
        ),
        migrations.AlterField(
            model_name='pnso',
            name='texto',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Texto'),
        ),
    ]
