# Generated by Django 4.1.7 on 2023-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0008_alter_pnso_image_pnso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='image_pnso',
            field=models.FileField(blank=True, null=True, upload_to='image_pnso'),
        ),
    ]
