# Generated by Django 4.1.7 on 2023-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNSO', '0009_alter_pnso_image_pnso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnso',
            name='estado',
            field=models.CharField(blank=True, choices=[('AA - NO CUENTA CON INFORMACION SUFICIENTE', 'AA'), ('BB - NO REQUIERE ACCION DE MITIGACION', 'BB'), ('CC - ACCION DE MITIGACION EN CURSO', 'CC '), ('DD - MITIGACION CONCLUIDA', 'DD'), ('NN - NO CORRESPONDE SER TRAMITADO COMO PNSO', 'NN')], max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
