# Generated by Django 4.1.7 on 2023-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pnso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='FECHA')),
                ('evento', models.CharField(choices=[('-------------------', '-'), ('BACHEO / DESPRENDIMIENTOS', 'BACHEO / DESPRENDIMIENTOS'), ('COLISION DE AERONAVE Y VEHICULO TERRESTRE', 'COLISION DE AERONAVE Y VEHICULO TERRESTRE'), ('COLISION DE AERONAVES', 'COLISION DE AERONAVES'), ('COLISION EQUIPOS TERRESTRES', 'COLISION EQUIPOS TERRESTRES'), ('DEFICIENCIAS BALIZAMIENTO ', 'DEFICIENCIAS BALIZAMIENTO '), ('DERRAMES DE HIDROCARBUROS', 'DERRAMES DE HIDROCARBUROS'), ('EXCURSION DE PISTA', 'EXCURSION DE PISTA'), ('FALTANTES', 'FALTANTES'), ('FOCO IGNEO', 'FOCO IGNEO'), ('FOD EN PISTA', 'FOD EN PISTA'), ('IMPACTO CON AVE', 'IMPACTO CON AVE'), ('INCURSION EN PISTA', 'INCURSION EN PISTA'), ('INTRUSION DE PERSONAS', 'INTRUSION DE PERSONAS'), ('PNSO', 'PNSO'), ('SEÑALETICA HORIZONTAL', 'SEÑALETICA HORIZONTAL'), ('SEÑALETICA VERTICAL', 'SEÑALETICA VERTICAL'), ('VANDALISMO CERCO', 'VANDALISMO CERCO'), ('VEHICULO PENALIZANDO POSICION', 'VEHICULO PENALIZANDO POSICION')], max_length=3000, verbose_name='EVENTO')),
                ('descripcion', models.CharField(max_length=3000, verbose_name='DESCRIPCION')),
                ('mitigacion', models.CharField(max_length=3000, verbose_name='MEDIDAS MITIGACION ADOPTADAS')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=15, verbose_name='ESTADO')),
                ('status', models.CharField(choices=[('REQUIERE SEGUIMIENTO', 'REQUIERE SEGUIMIENTO'), ('NO REQUIERE SEGUIMIENTO', 'NO REQUIERE SEGUIMIENTO')], max_length=30, verbose_name='STATUS')),
                ('seguimiento', models.CharField(max_length=3000, verbose_name='SEGUIMIENTO')),
                ('image_sms', models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='RELEVAMIENTO FOTOGRAFICO')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
    ]
