# Generated by Django 4.1.7 on 2023-02-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pnso',
            new_name='Sms',
        ),
    ]
