# Generated by Django 4.1.3 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_rename_pnso_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='image_sms',
            field=models.ImageField(blank=True, null=True, upload_to='image_sms', verbose_name='RELEVAMIENTO FOTOGRAFICO'),
        ),
    ]
