# Generated by Django 4.1.7 on 2023-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derrame', models.DateField(verbose_name='Fecha')),
                ('posicion', models.CharField(max_length=5, verbose_name='Posicion')),
                ('sustancia', models.CharField(max_length=100, verbose_name='Sustancia')),
                ('empresa', models.CharField(choices=[('5U - LADE', '5U'), ('AJ - AMERICAN JET', 'AJ'), ('AR - ARSA', 'AR'), ('FO - FLYBONDI', 'FO'), ('G3 - GOL', 'G3'), ('H2 - SKY', 'H2'), ('JA - JETSMART CHILE', 'JA'), ('JJ - LATAM BRASIL', 'JJ'), ('LA - LATAM AIRLINES', 'LA'), ('LP - LATAM PERU ', 'LP'), ('WJ - JETSMART ARGENTINA ', 'WJ'), ('ZP - PARANAIR ', 'ZP'), ('PRV - AV. GENERAL ', 'PRV')], max_length=50, verbose_name='Empresa')),
                ('equipo', models.CharField(max_length=10, verbose_name='Equipo')),
                ('metros', models.IntegerField(verbose_name='m2')),
                ('pintura_afectada', models.IntegerField(verbose_name='Pintura Afectada')),
                ('juntas', models.IntegerField(verbose_name='Juntas')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'DERRAME',
                'verbose_name_plural': 'DERRAMES',
            },
        ),
    ]
