# Generated by Django 4.1.7 on 2023-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DERRAMES', '0002_alter_derrame_metros_alter_derrame_sustancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derrame',
            name='juntas',
            field=models.CharField(max_length=5, verbose_name='Juntas'),
        ),
        migrations.AlterField(
            model_name='derrame',
            name='pintura_afectada',
            field=models.CharField(max_length=5, verbose_name='Pintura Afectada'),
        ),
    ]
