# Generated by Django 4.1.3 on 2023-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DERRAMES', '0004_alter_derrame_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derrame',
            name='empresa',
            field=models.CharField(choices=[('5U - LADE', '5U'), ('AJ - AMERICAN JET', 'AJ'), ('AR - ARSA', 'AR'), ('FO - FLYBONDI', 'FO'), ('G3 - GOL', 'G3'), ('H2 - SKY', 'H2'), ('JA - JETSMART CHILE', 'JA'), ('JJ - LATAM BRASIL', 'JJ'), ('LA - LATAM AIRLINES', 'LA'), ('LP - LATAM PERU ', 'LP'), ('WJ - JETSMART ARGENTINA ', 'WJ'), ('ZP - PARANAIR ', 'ZP'), ('PRV - AV. GENERAL ', 'PRV')], default='AR', max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='derrame',
            name='sustancia',
            field=models.CharField(choices=[('COMBUSTIBLE AERONAUTICO', 'COMBUSTIBLE AERONAUTICO'), ('COMBUSTIBLE TERRESTRE', 'COMBUSTIBLE TERRESTRE'), ('LIQUIDO HIDRAULICO', 'LIQUIDO HIDRAULICO'), ('ACEITES TERRESTRES', 'ACEITES TERRESTRES'), ('ACEITES AERONAUTICOS', 'ACEITES AERONAUTICOS'), ('OTROS', 'OTROS')], default='COMBUSTIBLE AERONAUTICO', max_length=100, verbose_name='Sustancia'),
        ),
    ]
