# Generated by Django 4.1.3 on 2023-03-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pos', models.DateField(verbose_name='Fecha')),
                ('posicion', models.CharField(choices=[('----', '----'), ('01', '01'), ('02', '02'), ('PAS-03', 'PAS-03'), ('PAS-04', 'PAS-04'), ('PAS-05', 'PAS-05'), ('PAS-06', 'PAS-06'), ('PAS-07', 'PAS-07'), ('PAS-08', 'PAS-08'), ('PAS-09', 'PAS-09'), ('PAS-10', 'PAS-10'), ('PAS-11', 'PAS-11'), ('PAS-12', 'PAS-12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('67', '67'), ('68', '68'), ('69', '69'), ('39', '39'), ('39A', '39A'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('66', '66')], max_length=10, verbose_name='POS')),
                ('lineas_de_guia', models.CharField(choices=[('----------------------', '----------------------'), ('EJE INGRESO', 'EJE INGRESO'), ('INDICADOR POSICION', 'INDICADOR POSICION'), ('INDICADOR STOP BAR', 'INDICADOR STOP BAR'), ('COMPLETA', 'COMPLETA'), ('CEBRADO', 'CEBRADO'), ('PUNTO PARKING PASARELA', 'PUNTO PARKING PASARELA'), ('ROJO Y BLANCO', 'ROJO Y BLANCO')], max_length=100, verbose_name='Lineas de Guia')),
                ('fecha_carteleria', models.DateField(verbose_name='Fecha')),
                ('carteleria', models.CharField(choices=[('----------------------', '----------------------'), ('EJE INGRESO', 'EJE INGRESO'), ('INDICADOR POSICION', 'INDICADOR POSICION'), ('INDICADOR STOP BAR', 'INDICADOR STOP BAR'), ('COMPLETA', 'COMPLETA'), ('CEBRADO', 'CEBRADO'), ('PUNTO PARKING PASARELA', 'PUNTO PARKING PASARELA'), ('ROJO Y BLANCO', 'ROJO Y BLANCO')], max_length=100, verbose_name='Carteleria')),
                ('fecha_lineas_seguridad', models.DateField(verbose_name='Fecha')),
                ('lineas_seguridad', models.CharField(choices=[('----------------------', '----------------------'), ('EJE INGRESO', 'EJE INGRESO'), ('INDICADOR POSICION', 'INDICADOR POSICION'), ('INDICADOR STOP BAR', 'INDICADOR STOP BAR'), ('COMPLETA', 'COMPLETA'), ('CEBRADO', 'CEBRADO'), ('PUNTO PARKING PASARELA', 'PUNTO PARKING PASARELA'), ('ROJO Y BLANCO', 'ROJO Y BLANCO')], max_length=100, verbose_name='Lineas de Seguridad')),
                ('sector', models.CharField(choices=[('-----', '-----'), ('PLAT. COMERCIAL', 'PLAT. COMERCIAL'), ('PLAT. INDUSTRIAL', 'PLAT. INDUSTRIAL'), ('PLAT. SUR', 'PLAT. SUR')], max_length=50, verbose_name='Sector')),
                ('pintado', models.CharField(choices=[('-----', '-----'), ('% 33', '% 33'), ('% 50', '% 50'), ('% 100', '% 100')], max_length=10, verbose_name='% Pintado')),
                ('estado', models.CharField(choices=[('-------', '-------'), ('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'PINTURA',
                'verbose_name_plural': 'PINTURA',
            },
        ),
    ]
