# Generated by Django 4.1.3 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentado', models.DateField(blank=True, null=True, verbose_name='Fecha Presentado')),
                ('titulo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Titulo')),
                ('fecha_aprobado', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobado')),
                ('estado', models.CharField(blank=True, choices=[('PRESENTADO', 'PRESENTADO'), ('APROBADO', 'APROBADO')], default='PRESENTADO', max_length=20, null=True, verbose_name='Estado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivo')),
            ],
            options={
                'verbose_name': 'ADR',
                'verbose_name_plural': 'ADRs',
            },
        ),
    ]
