# Generated by Django 4.1.7 on 2023-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bso', models.DateField(verbose_name='Fecha')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Orden')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
            ],
            options={
                'verbose_name': 'BSO',
                'verbose_name_plural': 'BSO',
            },
        ),
    ]
