# Generated by Django 4.1.7 on 2023-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSO', '0002_rename_image_bso_pdf_alter_bso_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bso',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
