# Generated by Django 4.1.3 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSO', '0003_alter_bso_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bso',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
