# Generated by Django 4.1.7 on 2023-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_protocolo', models.DateField(verbose_name='Fecha')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='profile_images')),
            ],
            options={
                'verbose_name': 'PROTOCOLO',
                'verbose_name_plural': 'PROTOCOLOS',
            },
        ),
    ]
