# Generated by Django 4.1.7 on 2023-04-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTOCOLO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='titulo',
            field=models.CharField(max_length=300, verbose_name='Titulo'),
        ),
    ]
