# Generated by Django 4.1.3 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTOCOLO', '0002_alter_protocolo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
