# Generated by Django 4.1.7 on 2023-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTOCOLO', '0003_alter_protocolo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='titulo',
            field=models.CharField(max_length=1000, verbose_name='Titulo'),
        ),
    ]
