# Generated by Django 4.1.3 on 2023-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteorologia', models.CharField(max_length=1000, verbose_name='meteorologia')),
            ],
        ),
    ]
