# Generated by Django 4.1.7 on 2023-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aviario', models.DateField(verbose_name='Fecha')),
                ('especie_ave', models.CharField(choices=[('CERNICALO', 'CERNICALO'), ('CHIMANGO', 'CHIMANGO'), ('GOLONDRINA', 'GOLONDRINA'), ('HALCONCITO COLORADO', 'HALCONCITO COLORADO'), ('LECHUZA', 'LECHUZA'), ('MURCIELAGO', 'MURCIELAGO'), ('PALOMA TORCAZA', 'PALOMA TORCAZA'), ('TERO', 'TERO'), ('OTROS', 'OTROS'), ('SIN EVIDENCIA', 'SIN EVIDENCIA')], max_length=100, verbose_name='Especie Aves')),
                ('empresa', models.CharField(choices=[('5U - LADE', '5U'), ('AJ - AMERICAN JET', 'AJ'), ('AR - ARSA', 'AR'), ('FO - FLYBONDI', 'FO'), ('G3 - GOL', 'G3'), ('H2 - SKY', 'H2'), ('JA - JETSMART CHILE', 'JA'), ('JJ - LATAM BRASIL', 'JJ'), ('LA - LATAM AIRLINES', 'LA'), ('LP - LATAM PERU ', 'LP'), ('WJ - JETSMART ARGENTINA ', 'WJ'), ('ZP - PARANAIR ', 'ZP'), ('PRV - AV. GENERAL ', 'PRV')], max_length=50, verbose_name='Empresa')),
                ('equipo', models.CharField(max_length=8, verbose_name='Equipo')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'IMPACTO',
                'verbose_name_plural': 'IMPACTOS',
            },
        ),
    ]
