# Generated by Django 4.1.7 on 2023-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Inicio',
                'verbose_name_plural': 'Inicio',
            },
        ),
    ]
